cache:
  config:
    default-configs:
      - cache-name: ONE_HOUR_CACHE
        timeToLiveSeconds: 3600
      - cache-name: TEN_MINUTES_CACHE
        timeToLiveSeconds: 60

  app-caches:
    appCachemap:
      serviceOne_cache: ONE_HOUR_CACHE
      serviceTwo_cache: TEN_MINUTES_CACHE

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: changeit
    sentinel:
      master: masterredis
      nodes:
        - xx.0.0.xx
    lettuce:
      shutdown-timeout: 200ms